# Generated by Django 5.2.1 on 2025-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
