# Generated by Django 5.2.1 on 2025-05-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_submission_verdict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
