# Generated by Django 5.2.1 on 2025-06-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_problem_setter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_problem_setter',
        ),
    ]
