# Generated by Django 5.2.1 on 2025-06-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_is_problem_setter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_problem_setter',
            field=models.BooleanField(default=False),
        ),
    ]
