# Generated by Django 5.2.1 on 2025-06-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='created_by',
        ),
    ]
